apiVersion: v1
kind: Service
metadata:
  name: second-app
spec:
  selector:
    app.kubernetes.io/name: second-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
