apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demoflask
  region: us-east-2

vpc:
  id: vpc-026b5a1d6705b4e98
  securityGroup: sg-090d4c6df60abfd75  # Replace with your EKS security group ID
  subnets:
    public:
      us-east-2a:
        id: subnet-09465b5d8911ce42c
      us-east-2b:
        id: subnet-01b48f04dd46b5476

nodeGroups:
  - name: demoflask
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
