apiVersion: v1
kind: Service
metadata:
  name: flasknode-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Port inside the container
      nodePort: 30000   # (Optional) NodePort (30000-32767)
