apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  type: LoadBalancer
  externalTrafficPolicy: Cluster  # Ensures external routing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000