apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: flask
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000